### PR TITLE
Add landing page, #39

### PR DESCRIPTION
**Pull request by gabrielbonner**
Add redirect on sign-in

### CODE REVIEW

**Comment by gabrielbonner** [comment]
There is noticeable gap between the image and the footer when you fiddle with the screen size in Chrome DevTools, but I figure I'll tackle that on the 'make site responsive ticket'.

I'm not sure I like the dodgerBlue color on the nav bar with this image, I'm going to experiment with a few more colors and the image opacity...

**Comment by appleJax** [comment]
I adjusted the styles a little, tried changing the color. I'm not sure if I like it, just wanted to see if you think that's the right direction or not.

**Comment by gabrielbonner** [comment]
Yeah, it's definitely looking better, although the logo font looks a little out of place now.  I like the muted colors on the landing page, but it's a bit drab once we get to /events.

Guess we kinda need to decide if we're going to go for 'classy' or for more of a t-shirt-and-jeans style...

**Comment by appleJax** [comment]
@gabrielbonner I agree, the brown doesn't look very good once you get off the landing page. I vote for steelblue.

**Comment by gabrielbonner** [comment]
@appleJax I can dig it.  What about Raleway for the font?  https://fonts.google.com/

**Comment by appleJax** [comment]
@gabrielbonner for the logo? The words make a huge difference as to how the font looks, so we probably shouldn't spend too much time comparing fonts until we settle on a name. Raleway looks pretty bad with Let's Meet Up though.

screen shot 2017-09-20 at 11 23 21 pm

**Comment by gabrielbonner** [comment]
@appleJax Makes sense, I'll work on the name next.  You think this one is ready to merge?

**Comment by appleJax** [comment]
@gabrielbonner can you look at my changes on the landing-page branch of the dev-magic repo? I tried to delete some code without changing the behavior or looks. The one exception is I have an alternate linear-gradient over the background image that looks a little cleaner to me. Let me know if you disagree with any changes I made.

**Comment by gabrielbonner** [comment]
@appleJax The white bar above the footer is more noticeable for me with the `min-height: 81vh`, I really wanted to merge this PR but I think I should try to fix that issue first.  :S

I like the rest though, and your gradient makes more sense.

screen shot 2017-09-21 at 11 40 32 am

**Comment by appleJax** [comment]
@gabrielbonner ok, I pushed up another commit. I think it may actually be impossible to make the landing page image always take up exactly the space between the nav and footer if the landingPage is a react component. The fact that react wraps the `landing-page-div` in another div really ties our hands. My solution was to just make the landing page a template instead. Let me know if it looks right on your computer.

**Comment by gabrielbonner** [comment]
@appleJax Great success, merge at will.  Thanks for doing that, I wouldn't have been able to get to it until tonight.  👍

**Pull request closed without merging**
